###
POST http://localhost:8000/api/auth/sign-up/email
Accept: application/json
Content-Type: application/json

{
  "email": "hello@towaanu.com",
  "password": "secret55555",
  "name": "hello"
}

### Signin
POST http://localhost:8000/api/auth/sign-in/email
Accept: application/json
Content-Type: application/json

{
  "email": "hello@towaanu.com",
  "password": "secret55555"
}
> {%
  -- lua
  -- save the new set authenticated session
  client.global.session = response.cookies["better-auth.session_token"].value
%}

### Me
run #Signin

GET http://localhost:8000/api/users/me
Accept: application/json
Cookie: better-auth.session_token={{session}}
